# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol.proto',
  package='protocol',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eprotocol.proto\x12\x08protocol\"\xa9\x01\n\x07Request\x12+\n\tcalibrate\x18\x01 \x01(\x0b\x32\x16.protocol.CalibrateReqH\x00\x12\x32\n\rrelative_move\x18\x02 \x01(\x0b\x32\x19.protocol.RelativeMoveReqH\x00\x12\x32\n\rabsolute_move\x18\x03 \x01(\x0b\x32\x19.protocol.AbsoluteMoveReqH\x00\x42\t\n\x07request\"0\n\x0c\x43\x61librateReq\x12\x11\n\tdirection\x18\x01 \x02(\x08\x12\r\n\x05limit\x18\x02 \x02(\r\"$\n\x0fRelativeMoveReq\x12\x11\n\tincrement\x18\x01 \x02(\x05\"#\n\x0f\x41\x62soluteMoveReq\x12\x10\n\x08position\x18\x01 \x02(\r\"\xae\x01\n\x08Response\x12,\n\tcalibrate\x18\x01 \x01(\x0b\x32\x17.protocol.CalibrateRespH\x00\x12\x33\n\rrelative_move\x18\x02 \x01(\x0b\x32\x1a.protocol.RelativeMoveRespH\x00\x12\x33\n\rabsolute_move\x18\x03 \x01(\x0b\x32\x1a.protocol.AbsoluteMoveRespH\x00\x42\n\n\x08response\" \n\rCalibrateResp\x12\x0f\n\x07success\x18\x01 \x02(\x08\"$\n\x10RelativeMoveResp\x12\x10\n\x08position\x18\x01 \x02(\r\"\x12\n\x10\x41\x62soluteMoveResp'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='protocol.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='calibrate', full_name='protocol.Request.calibrate', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relative_move', full_name='protocol.Request.relative_move', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='absolute_move', full_name='protocol.Request.absolute_move', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='protocol.Request.request',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=29,
  serialized_end=198,
)


_CALIBRATEREQ = _descriptor.Descriptor(
  name='CalibrateReq',
  full_name='protocol.CalibrateReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='protocol.CalibrateReq.direction', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='protocol.CalibrateReq.limit', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=248,
)


_RELATIVEMOVEREQ = _descriptor.Descriptor(
  name='RelativeMoveReq',
  full_name='protocol.RelativeMoveReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='increment', full_name='protocol.RelativeMoveReq.increment', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=286,
)


_ABSOLUTEMOVEREQ = _descriptor.Descriptor(
  name='AbsoluteMoveReq',
  full_name='protocol.AbsoluteMoveReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='protocol.AbsoluteMoveReq.position', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=323,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='protocol.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='calibrate', full_name='protocol.Response.calibrate', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relative_move', full_name='protocol.Response.relative_move', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='absolute_move', full_name='protocol.Response.absolute_move', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='protocol.Response.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=326,
  serialized_end=500,
)


_CALIBRATERESP = _descriptor.Descriptor(
  name='CalibrateResp',
  full_name='protocol.CalibrateResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='protocol.CalibrateResp.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=534,
)


_RELATIVEMOVERESP = _descriptor.Descriptor(
  name='RelativeMoveResp',
  full_name='protocol.RelativeMoveResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='protocol.RelativeMoveResp.position', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=536,
  serialized_end=572,
)


_ABSOLUTEMOVERESP = _descriptor.Descriptor(
  name='AbsoluteMoveResp',
  full_name='protocol.AbsoluteMoveResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=592,
)

_REQUEST.fields_by_name['calibrate'].message_type = _CALIBRATEREQ
_REQUEST.fields_by_name['relative_move'].message_type = _RELATIVEMOVEREQ
_REQUEST.fields_by_name['absolute_move'].message_type = _ABSOLUTEMOVEREQ
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['calibrate'])
_REQUEST.fields_by_name['calibrate'].containing_oneof = _REQUEST.oneofs_by_name['request']
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['relative_move'])
_REQUEST.fields_by_name['relative_move'].containing_oneof = _REQUEST.oneofs_by_name['request']
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['absolute_move'])
_REQUEST.fields_by_name['absolute_move'].containing_oneof = _REQUEST.oneofs_by_name['request']
_RESPONSE.fields_by_name['calibrate'].message_type = _CALIBRATERESP
_RESPONSE.fields_by_name['relative_move'].message_type = _RELATIVEMOVERESP
_RESPONSE.fields_by_name['absolute_move'].message_type = _ABSOLUTEMOVERESP
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['calibrate'])
_RESPONSE.fields_by_name['calibrate'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['relative_move'])
_RESPONSE.fields_by_name['relative_move'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['absolute_move'])
_RESPONSE.fields_by_name['absolute_move'].containing_oneof = _RESPONSE.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['CalibrateReq'] = _CALIBRATEREQ
DESCRIPTOR.message_types_by_name['RelativeMoveReq'] = _RELATIVEMOVEREQ
DESCRIPTOR.message_types_by_name['AbsoluteMoveReq'] = _ABSOLUTEMOVEREQ
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['CalibrateResp'] = _CALIBRATERESP
DESCRIPTOR.message_types_by_name['RelativeMoveResp'] = _RELATIVEMOVERESP
DESCRIPTOR.message_types_by_name['AbsoluteMoveResp'] = _ABSOLUTEMOVERESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Request)
  })
_sym_db.RegisterMessage(Request)

CalibrateReq = _reflection.GeneratedProtocolMessageType('CalibrateReq', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATEREQ,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:protocol.CalibrateReq)
  })
_sym_db.RegisterMessage(CalibrateReq)

RelativeMoveReq = _reflection.GeneratedProtocolMessageType('RelativeMoveReq', (_message.Message,), {
  'DESCRIPTOR' : _RELATIVEMOVEREQ,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:protocol.RelativeMoveReq)
  })
_sym_db.RegisterMessage(RelativeMoveReq)

AbsoluteMoveReq = _reflection.GeneratedProtocolMessageType('AbsoluteMoveReq', (_message.Message,), {
  'DESCRIPTOR' : _ABSOLUTEMOVEREQ,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:protocol.AbsoluteMoveReq)
  })
_sym_db.RegisterMessage(AbsoluteMoveReq)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:protocol.Response)
  })
_sym_db.RegisterMessage(Response)

CalibrateResp = _reflection.GeneratedProtocolMessageType('CalibrateResp', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATERESP,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:protocol.CalibrateResp)
  })
_sym_db.RegisterMessage(CalibrateResp)

RelativeMoveResp = _reflection.GeneratedProtocolMessageType('RelativeMoveResp', (_message.Message,), {
  'DESCRIPTOR' : _RELATIVEMOVERESP,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:protocol.RelativeMoveResp)
  })
_sym_db.RegisterMessage(RelativeMoveResp)

AbsoluteMoveResp = _reflection.GeneratedProtocolMessageType('AbsoluteMoveResp', (_message.Message,), {
  'DESCRIPTOR' : _ABSOLUTEMOVERESP,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:protocol.AbsoluteMoveResp)
  })
_sym_db.RegisterMessage(AbsoluteMoveResp)


# @@protoc_insertion_point(module_scope)
